global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'queueflow-api-server'
    static_configs:
      - targets: ['api-server:4000', 'localhost:4000']

  - job_name: 'queueflow-worker-service'
    static_configs:
      - targets: ['worker-service:4001', 'localhost:4001']

  - job_name: 'queueflow-scheduler-service'
    static_configs:
      - targets: ['scheduler-service:4002', 'localhost:4002']
